openedx/codejail

codejail/jail_code.py
codejail/tests/test_jail_code.py

@adampalay @feanil This will give us 152 as an exit code when the CPU limit is reached, rather than the more generic 137.

Set CPU limit to get better info. More specific tests

---

Makefile
README.rst
codejail/django_integration.py
codejail/jail_code.py
codejail/proxy.py
codejail/safe_exec.py
codejail/subproc.py
codejail/tests/test_jail_code.py
memory_stress.py
proxy_main.py

When spawning subprocesses, fork() will fail if the memory of the parent
can't be duplicated in the child. This means large long-lived processes
will have problems using CodeJail repeatedly.
This introduces a long-lived proxy subprocess which then spawns the
actual subprocesses.  Because the proxy process starts small and stays
small, it will be able to spawn subprocesses even when the parent
process grows large.
The use of the proxy process is controlled by a "PROXY" limit, which
should be 0 or 1.  If neither is set, then the CODEJAIL_PROXY
environment variable determines whether the proxy is used.
BTW: before the rebase, the head was
0e9c49336d5b2c10d1429559c640d37d6eea171c if you want to see the
progression of commits to get this to work. :)

Optionally use a proxy process to spawn subprocesses

---

codejail/jail_code.py
codejail/tests/helpers.py
codejail/tests/test_jail_code.py
pylintrc

`subprocess` tries to treat `TMPDIR=tmp` as the executable if it is passed as the first argument, and raises an `OSError` because no file by that name exists.  This moves the environment variable to the environment, where it belongs, but adds it to the sudo command when that is supplied to work around oddities in sudo's environment handling.  This work is preparatory to [TNL-4843](https://openedx.atlassian.net/browse/TNL-4843).
@edx/devops : Because codejail delves into user permissions, system configuration, and other things that are generally in your wheelhouse, I want you to be aware of what I'm up to, and can stop me if I do something crazy.

Fix command line handling so it works when no user is specified.

---

codejail/__init__.py
codejail/django_integration.py
codejail/integration.py
codejail/tests/test_integration.py
codejail/tests/test_jail_code.py
setup.py

Apparently, there were zero tests on django integration, and I introduced an error into that code, which was causing failures in edx-platform. Additionally, the django integration only worked with a single codejail named "python."  This allows multiple jails to be configured in django settings, but maintains backwards compatibility with existing configuration.
(There are further errors on edx-platform due to jails not being configured for tests.  The jails were previously configured using codejail's unsafe autoconfiguration mechanism.  Fixing that needs to happen on the edx-platform side, and is being addressed in https://github.com/edx/edx-platform/pull/12891)

Fixing django integration.

---

requirements/sandbox.txt

Adding the two dependencies used in testing codejail sandboxes. These need to be installed in the sandboxes before AppArmor is activated.

requirements for building sandboxes

---

codejail/tests/test_jail_code.py

One test was regularly failing due to it timing out before it could execute the jailed code. Needed to up the execution time limit. Doing so broke another test, which requires a the default time limit of `1`. These should be reset by the `teardown` method in the test class, but the test kept failing. I can dig in a little further, but this unblocks the work to run python-modernize.

wait longer in flaky test

---

codejail/jail_code.py
codejail/safe_exec.py
codejail/tests/test_jail_code.py
codejail/tests/test_safe_exec.py
setup.py

This gets the tests passing in python3.
There are a couple of things to note here:
* Most of the fixes are modernizing the code strings in the tests themselves and a lot of conversions due to the changes in bytes/strings in python 3.
* Some exceptions changed from 2 to 3, so now you need to check the python version in the test.
* I had to `skip test_crash_cpython` for now, as it needs some rethinking with regards of how to get it to work in Python 3
* we shifted the main dev branch from `edx-platform-master` to `master`, which broke datree's brain, so you can probably disregard the failure.

python modernize pt 2

---

codejail/safe_exec.py
codejail/tests/test_safe_exec.py
setup.py

As a part of the python3 conversion, we added logic to try to convert
bytestrings to unicode strings.  This had a problem because not all
bytestrings that are produced as a part of the context passed into and
out of the jailed code execution is actually unicode strings.  In some
cases this was resulting in a unicode decode error.
Before this code existed we used to just drop any nonstandard types and
also only keep complex types(list,dict,tuples) that were easily
jsonable.  In python2 this was fine because byte strings would
automatically get coerced to unicode strings.  However in python3 this
will throw errors.  So if we don't explicitly try to convert all the
byte strings to unicode, we could stop passing back data that we
previously used to pass in.
The first iteration of this code …

Improve Serialization Logic

---

tox.ini

Add py38 to tox.ini so we can run python 3.8 tests in jenkins.
Related to https://openedx.atlassian.net/browse/BOM-1591
I think that we need an additional step in the jenkins configuration

[BD-6] Add py38 to tox

---

codejail/jail_code.py
setup.py

Change the way to check if it is running in a virtualenv in order to be compatible with virtualenv>20.0.0 and virtualenv<20.0.0 (currently used in the platform)
I separated the change in three commits, so you can see that
1- in the first commit (using virtualenv<20.0.0) it is failing,
2- In the second commit, the changes fixed the problem for virtualenv<20.0.0
3- in the third commit we are using again virtualenv>20.0.0 and it is working

[BD-6] Fix check of virtualenv for virtualenv<20.0.0

---

setup.py

Currently, setup.py yields a non-working installation if the "six" package is not already installed. This PR adds "six" to install_requires so installations in minimal environments work out the box.

Add required dependency on "six" package

---

AUTHORS
codejail/django_integration.py
codejail/django_integration_utils.py
codejail/jail_code.py
codejail/safe_exec.py
codejail/tests/test_django_integration_utils.py
codejail/tests/util.py
setup.py

We allow `limit_overrides_context` to be passed in to `jail_code`.
If `settings.CODE_JAIL['limit_overrides'][limit_overrides_context]` exists, then prefer those values to the ones in `settings.CODE_JAIL['limits']`.
In the [edx-platform PR](https://github.com/edx/edx-platform/pull/25483), we pass in the course run id is as the `limit_overrides_context`.
Per @nedbat 's comment, the PROXY setting cannot be overridden. An error will be logged and the override will be ignored.
(also, this removes outdated AUTHORS file, as we've done with most other repos)
* Customer request for root cause (codejail times out sometimes): https://openedx.atlassian.net/browse/CR-2519
* Customer request for a workaround for a specific course run: https://openedx.atlassian.net/browse/CR-2862
* TNL ticket for …

Allow context-specific resource limits to be provided

---

.gitignore
Makefile
codejail/django_integration.py
codejail/jail_code.py
codejail/proxy.py
codejail/safe_exec.py
codejail/subproc.py
codejail/tests/doit.py
codejail/tests/test_django_integration_utils.py
codejail/tests/test_jail_code.py
codejail/tests/test_json_safe.py
codejail/tests/test_safe_exec.py
codejail/util.py
memory_stress.py
proxy_main.py
pylintrc
setup.cfg
tox.ini

https://github.com/edx/codejail/pull/98 involves refactoring several files. It'd be helpful to be able to use pylint to catch anything I miss in that refactoring.
This cleans up all of the quality violations in codejail and adds a `make quality` target, which runs pycodestyle, isort, and pylint on all python files in the repo.
This Jenkins DSL PR would enable quality checking on new CodeJail PRs: https://github.com/edx/jenkins-job-dsl/pull/1166

Add tox/Makefile quality target; fix quality violations

---

Makefile
codejail/django_integration.py
codejail/jail_code.py
codejail/proxy.py
codejail/safe_exec.py
codejail/subproc.py
codejail/tests/test_jail_code.py
requirements/development.txt
requirements/pip_tools.txt
requirements/sandbox.txt
requirements/testing.in
requirements/testing.txt
requirements/tox.txt
setup.py

This includes two commits. Only #2 includes functionality change.
Since my last codejail PR, I made a jenkins-job-dsl change to add quality checks to these PRs. This commit makes some tweaks so that the quality build will actually pass.
Adds a logging statement to help me dig into my "Celery-workers-don't-have-codejail-configured" hypothesis. Also upgrades codejail from 3.1.0 to 3.1.1.
From the commit message:
```
Log effective resource limits for every jail_code call
We are curious whether async jail_code calls on Celery workers
have different resource limit configurations than synchronous
calls on LMS/Studio. We suspect it may be different
because codejail is configured via a Django Middleware, which
may not be initialized for Celery workers.
``` …

Log effective resource limits for every jail_code call; also, fix build

---

codejail/jail_code.py
setup.py

```
The logging statement added in 3.1.1, and modified in
3.1.2, was typoed.
Bump version to 3.1.3
```
Whoops, the logging message I added in https://github.com/edx/codejail/pull/103 was messed up. This fixes it, and also simplifies the logging statement itself a bit.
The corresponding edx-platform version bump is here: https://github.com/edx/edx-platform/pull/25540
https://openedx.atlassian.net/browse/TNL-7649

Fix 'Preparing to execute jailed code' log message

---

setup.py

Updates name of the package to edx-codejail as codejail isn't allowed on PyPI
For reference https://github.com/edx/codejail/runs/2352964134?check_suite_focus=true#step:8:25

build: update package name to edx-codejail

---

.github/workflows/ci.yml
Dockerfile
apparmor-profiles/home.sandbox.codejail_sandbox-python3.8.bin.python
sudoers-file/01-sandbox

The `codejail CI` jobs are essentially the last public-facing jobs on https://build.testeng.edx.org/ , which we really want to shut down or at least bring behind the VPN. This PR moves the CI jobs from Jenkins to Github Actions utilizing Docker Image and parsing `apparmor` profile using Github VM. Jenkins checks will be removed in a subsequent PR.

Shift codejail CI to docker image

---

.github/workflows/push-docker-image.yml
Dockerfile

This PR improves the existing codejail Dockerfile. We copy code files after installing the requirements so that changes to code don't bust the cached requirements layers in docker image.
This PR also adds `git` package in Dockerfile so that we can use it to fetch recent changes while running tests on PRs.
Finally this PR also adds a push workflow to push latest CI image to ECR.

Improve Dockerfile and add push workflow

---

.github/workflows/ci.yml
codejail/tests/test_safe_exec.py

Previously there was a bug in codejail CI where tests were being run on the code state which was pushed in the CI image when the image was built and not on the updated code content in the new PRs or on master. 
This PR fixes the bug and instead of pulling the image in the step where we run container, we now pull the image beforehand and then using that image as cache we build/update the image again effectively integrating new change into the image.

Pull latest code changes in codejail CI

---

requirements/sandbox.txt

Updates `django` from `3.2.13` to `3.2.17`

chore: Updating Python Requirements

---

README.rst
codejail/jail_code.py

This still doesn't work as described, as codejail's confinement still denies it the ability to create a temp directory, but it's closer.
- Specify the use of `--copies` when setting up the sandbox virtualenv
- Include the `user` argument to work around TMPDIR bug (https://github.com/openedx/codejail/issues/162) and link to the issue from a code comment
- Use an unambiguous test for safe/usafe configuration (return the value using jailed globals, and bypass some issues with output streams)
- Ensure that reading codejail checkout is permitted by apparmor
Also:
- Use the venv module rather than the virtualenv command, for better compatibility with varying system configurations
- Don't bother activating virtualenv, just call its pip directly
- Note the ordinarily-unsafe presence of find in …

docs: Various fixes to codejail setup instructions (copies, user)

---

.github/workflows/pypi-release.yml

As it mentioned in the gh-action-pypi-publish repo, the master branch version has been sunset and we should use release/v1.

fix: master branch sunset

---

README.rst

Warn operators about areas where they will need to take extra care.

docs: Add Limitations section to README

---

codejail/proxy.py

I just grabbed the commit message for f4cb95bb2bdb819cde/PR #36. I haven't actually verified whether this is still accurate -- note that this is from 2015, written for Python 2. For all I know this performance concern is no longer relevant. It also may not be relevant for codejail-service, which is a much smaller process than edxapp.

docs: Document the PROXY setting and why you would want to use it

---

.github/workflows/ci.yml
Dockerfile
Makefile
codejail/tests/test_django_integration_utils.py
requirements/constraints.txt
requirements/development.txt
requirements/pip.txt
requirements/sandbox.in
requirements/sandbox.txt
requirements/testing.in
requirements/testing.txt
requirements/tox.txt
tox.ini

The only usage of Django is in ConfigureCodeJailMiddleware. A small test
to check that the middleware can be correctly instantiated is included.

feat: support for django 5.2

---

README.rst

- Remove descriptions of `SAND_PACK`, `UNTRUSTED_PACK`, and `OSPACK`, as these were not referenced anywhere else.  Replace with a description of the virtualenv and the file structure of the ephemeral sandbox that jail_code creates.
- Clarify Python version app/jail distinction.
- Add recommendation for runtime self-tests.
- Minor formatting and fixes.

docs: General doc updates
